#https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-launch-pub.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch Template EC2 Server for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------

Metadata: {}
Conditions: {}


Parameters:
#===========================================

#--- Server Public Subnet 
#-------------------------------------------
  PublicSubnetIdA:
    Description: Public Subnet ID AZ-A
    Type: AWS::EC2::Subnet::Id
#--- Public Security Group Resource ID
#-------------------------------------------
  PublicSgResourceId:
    Description: Public Security Group ID AZ-A
    Type: AWS::EC2::SecurityGroup::Id
#-------------------------------------------



Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# LAUNCH TEMPLATE DEFINITION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Private Launch Template 
#-------------------------------------------
  PublicLaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Properties:
      LaunchTemplateName: "dh.cform.openvpn-launch-tmplt-pub"
      LaunchTemplateData:
        IamInstanceProfile:
          Name: "dh.InstProfile.Managed.SysAdmin"
        SecurityGroupIds: 
        - !Ref PublicSgResourceId
        ImageId: "ami-0d4c3eabb9e72650a"
        InstanceType: "t2.micro"
        KeyName: !Sub "dh.SSH.Default_${AWS::Region}"
        TagSpecifications: 
        - 
          ResourceType: "instance"
          Tags: 
          - 
            Key: "Name"
            Value: "openvpn-public"
        - 
          ResourceType: "volume"
          Tags: 
          - 
            Key: "Name"
            Value: "openvpn-public"
        UserData:
          Fn::Base64:
            !Sub |
              #!/bin/bash -xe
              # Update Packages, inc. aws-cfn-bootstrap
              yum update -y
              # Start cfn-init
              /opt/aws/bin/cfn-init -v -s ${AWS::StackId} -r PublicLaunchTemplate --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
              # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
              /opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
              # All done so signal success
              /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource PublicLaunchTemplate --region ${AWS::Region}
    Metadata:
      Comment: Metadata description here.
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            "/var/www/html/index.html":
              content: !Sub |
                Hello from ${AWS::StackId}.
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true

#-------------------------------------------



#Outputs: {}
Outputs:
#===========================================


#---Top Level VPCID Export
#-------------------------------------------
  PubLaunchTmpltId:
    Description: ID of the launch template.
    Value:
      Ref: PublicLaunchTemplate
#    Export:
#      Name:
#        Fn::Sub: ${AWS::StackName}-VPCID
#---Public Subnet AZ-A Export
#-------------------------------------------