# https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-sg.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  An OpenVPN implementation that comprises:
  Highly Available EC2 Instance bla bla.
  Autoscaling Group bla bla.
  Isolated Certificate Authority bla bla.
  Nested Stack as follows:
  Bla Bla.
  Inputs:
  Bla Bla.
  Outputs.
  Bla Bla.
#-------------------------------------------


Metadata: {}

Conditions:
  HasNot: !Equals [ 'true', 'false']


Parameters:
#===========================================

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SUBNET CIDR DEFINITIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR Block for the VPC
    Type: String
#--- AZ-A Public Subnet
#-------------------------------------------
  PublicSubnetACIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR Block for the public DMZ subnet A located in Availability Zone A.
    Type: String
#--- AZ-B Public Subnet
#-------------------------------------------
  PublicSubnetBCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR Block for the public DMZ subnet B located in Availability Zone B
    Type: String
#--- AZ-A Private Subnet
#-------------------------------------------
  PrivateSubnetACIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet A located in Availability Zone A.
    Type: String
#--- AZ-B Private Subnet
#-------------------------------------------
  PrivateSubnetBCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet B located in Availability Zone B.
    Type: String
#-------------------------------------------



Resources:
#===========================================

  NullResource:
    Type: 'Custom::NullResource'
    Condition: HasNot
#-------------------------------------------


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# NESTED STACKS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- VPC Definition
#-------------------------------------------
  VPCDef:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-vpc.yaml
      Parameters:
        VPCCIDR:
          Ref: VPCCIDR
        PublicSubnetACIDR:
          Ref: PublicSubnetACIDR
        PublicSubnetBCIDR:
          Ref: PublicSubnetBCIDR
        PrivateSubnetACIDR:
          Ref: PrivateSubnetACIDR
        PrivateSubnetBCIDR:
          Ref: PrivateSubnetBCIDR
      TimeoutInMinutes: 5
#-------------------------------------------

#--- Public/Private NACLs
#-------------------------------------------
  NaclDefs:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-nacl.yaml
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
        VPCCIDR:
          Ref: VPCCIDR          
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSubnetIdB:
          !GetAtt VPCDef.Outputs.PublicSubnetIdB
        PrivateSubnetIdA:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdA
        PrivateSubnetIdB:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdB
      TimeoutInMinutes: 5
#-------------------------------------------

#--- Public/Private Security Groups
#-------------------------------------------
  SgDefs:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-sg.yaml
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
        VPCCIDR:
          Ref: VPCCIDR
#        ApplicationName:
#          Ref: AWS::StackName
      TimeoutInMinutes: 5
#-------------------------------------------


#--- Private/Public EC2 Instances
#-------------------------------------------
  InstancePubDef:
    Type: AWS::CloudFormation::Stack
    DependsOn: SgDefs
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-pub.yaml
      Parameters:
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 5
#-------------------------------------------



#-------------------------------------------

#Outputs: {}
Outputs:
#===========================================

  ExportsStackName:
    Value: !Ref 'AWS::StackName'
    Export:
      Name: !Sub 'ExportsStackName-${AWS::StackName}'

#--- VPC CIDR Export
#-------------------------------------------
  VPCCIDR:
    Description: VPC CIDR
    Value:
      Ref: VPCCIDR
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-VPCCIDR
