# https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-vpc.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested Stack: VPCDef. VPC & Multi AZ Public-Private Subnet Definitions'

Metadata: {}
Conditions: {}


Parameters:
#===========================================

#--- CIDR Strings
#-------------------------------------------
  VPCCIDR:
    Description: CIDR Block for the VPC
    Type: String
#-------------------------------------------
  PublicSubnetACIDR:
    Description: CIDR Block for the public DMZ subnet A located in Availability Zone A.
    Type: String
#-------------------------------------------
  PublicSubnetBCIDR:
    Description: CIDR Block for the public DMZ subnet B located in Availability Zone B
    Type: String
#-------------------------------------------
  PrivateSubnetACIDR:
    Description: CIDR block for private subnet A located in Availability Zone A.
    Type: String
#-------------------------------------------
  PrivateSubnetBCIDR:
    Description: CIDR block for private subnet B located in Availability Zone B.
    Type: String
#-------------------------------------------



Resources:
#===========================================

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# TOP LEVEL CIDR DEFINITION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- VPC Definition
#-------------------------------------------
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock:
        Ref: VPCCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
#-------------------------------------------


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SUBNET DEFINITIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- AZ-A Public Subnet
#-------------------------------------------
  PublicSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock:
        Ref: PublicSubnetACIDR
      MapPublicIpOnLaunch: true
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: Public Subnet AZ-A
      AvailabilityZone:
        'Fn::Select':
          - '0'
          - 'Fn::GetAZs':
              Ref: 'AWS::Region'
#--- AZ-B Public Subnet
#-------------------------------------------
  PublicSubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock:
        Ref: PublicSubnetBCIDR
      MapPublicIpOnLaunch: true
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: Public Subnet AZ-B
      AvailabilityZone:
        'Fn::Select':
          - '1'
          - 'Fn::GetAZs':
              Ref: 'AWS::Region'
#--- AZ1 Private Subnet
#-------------------------------------------
  PrivateSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock:
        Ref: PrivateSubnetACIDR
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: Private Subnet AZ-A
      AvailabilityZone:
        'Fn::Select':
          - '0'
          - 'Fn::GetAZs':
              Ref: 'AWS::Region'
#--- AZ-B Private Subnet
#-------------------------------------------
  PrivateSubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock:
        Ref: PrivateSubnetBCIDR
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: Private Subnet AZ-B
      AvailabilityZone:
        'Fn::Select':
          - '1'
          - 'Fn::GetAZs':
              Ref: 'AWS::Region'
#-------------------------------------------


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ROUTE TABLE DEFINITIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Public Route Table
#-------------------------------------------
  RouteTablePublic:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: Public Route Table
  RouteTablePublicAssociationA:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      SubnetId:
        Ref: PublicSubnetA
  RouteTablePublicAssociationB:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId:
        Ref: RouteTablePublic
      SubnetId:
        Ref: PublicSubnetB
  RouteTablePublicRoute0:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: RouteTablePublic
      GatewayId:
        Ref: Igw

#--- Private A Route Table
#-------------------------------------------
  RouteTablePrivateA:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: Private Route Table A
  RouteTablePrivateAAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId:
        Ref: RouteTablePrivateA
      SubnetId:
        Ref: PrivateSubnetA
  RouteTablePrivateARoute0:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: RouteTablePrivateA
      NatGatewayId:
        Ref: NatGw1

#--- Private B Route Table
#-------------------------------------------
  RouteTablePrivateB:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: Private Route Table B
  RouteTablePrivateBAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      RouteTableId:
        Ref: RouteTablePrivateB
      SubnetId:
        Ref: PrivateSubnetB
  RouteTablePrivateBRoute0:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: RouteTablePrivateB
      NatGatewayId:
        Ref: NatGw1
#-------------------------------------------


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# GATEWAY DEFINITIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Internet Gateway
#-------------------------------------------
  Igw:
    Type: 'AWS::EC2::InternetGateway'
    Properties: {}
#-------------------------------------------
  IGWAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: Igw


#--- NAT Gateway
#-------------------------------------------
  NatGw1:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      SubnetId:
        Ref: PublicSubnetA
      AllocationId:
        'Fn::GetAtt':
          - NatGw1ElasticIP
          - AllocationId
#-------------------------------------------
  NatGw1ElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc
#-------------------------------------------


Outputs:
#===========================================


#---Top Level VPCID Export
#-------------------------------------------
  VPCID:
    Description: VPC ID
    Value:
      Ref: VPC
#    Export:
#      Name:
#        Fn::Sub: ${AWS::StackName}-VPCID
#---Public Subnet AZ-A Export
#-------------------------------------------
  PublicSubnetIdA:
    Description: Public Subnet ID AZ-A
    Value:
      Ref: PublicSubnetA
#    Export:
#      Name: 
#        Fn::Sub: ${AWS::StackName}-PublicSubnetIdA
#---Public Subnet AZ-B Export
#-------------------------------------------
  PublicSubnetIdB:
    Description: Public Subnet ID AZ-B
    Value:
      Ref: PublicSubnetB
#    Export:
#      Name: 
#        Fn::Sub: ${AWS::StackName}-PublicSubnetIdB
#---Private Subnet AZ-A Export
#-------------------------------------------
  PrivateSubnetIdA:
    Description: Private Subnet ID AZ-A
    Value:
      Ref: PrivateSubnetA
#    Export:
#      Name: 
#        Fn::Sub: ${AWS::StackName}-PrivateSubnetIdA
#---Private Subnet AZ-B Export
#-------------------------------------------
  PrivateSubnetIdB:
    Description: Private Subnet ID AZ-B
    Value:
      Ref: PrivateSubnetB
#    Export:
#      Name: 
#        Fn::Sub: ${AWS::StackName}-PrivateSubnetIdB
#-------------------------------------------
