#https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-launch-pub.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch Template EC2 Server for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------

Metadata: {}
Conditions: {}


Parameters:
#===========================================

#--- AWS-Specific Parameter Type
#-------------------------------------------
  PublicSubnetIdA:
    Description: Public Subnet ID AZ-A
    Type: AWS::EC2::Subnet::Id
#-------------------------------------------
#--- Public Security Group Resource ID
#-------------------------------------------
  PublicSgResourceId:
    Description: Public Security Group ID AZ-A
    Type: AWS::EC2::SecurityGroup::Id
#-------------------------------------------


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# PUBLIC EC2 DEFINITION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Public EC2 Instance
#-------------------------------------------

  PublicEC2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:    
        Count: 1
        Timeout: "PT5M"
    Properties:
      AvailabilityZone:
        'Fn::Select':
          - '0'
          - 'Fn::GetAZs':
              Ref: 'AWS::Region'
      DisableApiTermination: false
      IamInstanceProfile: "dh.InstProfile.Managed.SysAdmin"
      ImageId: "ami-0d4c3eabb9e72650a"
      InstanceType: "t2.micro"
      KeyName: !Sub "dh.SSH.Default_${AWS::Region}"
      Monitoring: false
      SubnetId:
        Ref: PublicSubnetIdA
      SecurityGroupIds:
        - !Ref PublicSgResourceId
      Tags:
        -
          Key: "Name"
          Value: "openvpn-public"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            # Update Packages, inc. aws-cfn-bootstrap
            yum update -y
            # Start cfn-init
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource PublicEC2Instance --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
            # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
            #/opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
            # All done so signal success
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource PublicEC2Instance --region ${AWS::Region}
    Metadata:
      Comment: Metadata description here.
      AWS::CloudFormation::Init:
        config:
          packages:
            yum:
              httpd: []
          files:
            "/var/www/html/index.html":
              content: !Sub |
                <h1>Hello from ${AWS::StackId}<h1>
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true

#-------------------------------------------



Outputs: {}
#Outputs:
#===========================================


#---Top Level VPCID Export
#-------------------------------------------
#  PubLaunchTmpltId:
#    Description: ID of the launch template.
#    Value:
#      Ref: PublicLaunchTemplate
#    Export:
#      Name:
#        Fn::Sub: ${AWS::StackName}-VPCID
#---Public Subnet AZ-A Export
#-------------------------------------------