#https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-launch-pub.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch Template EC2 Server for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------

Metadata: {}
Conditions: {}


Parameters:
#===========================================

#--- AWS-Specific Parameter Type
#-------------------------------------------
  PublicSubnetIdA:
    Description: Public Subnet ID AZ-A
    Type: AWS::EC2::Subnet::Id
#-------------------------------------------
#--- Public Security Group Resource ID
#-------------------------------------------
  PublicSgResourceId:
    Description: Public Security Group ID AZ-A
    Type: AWS::EC2::SecurityGroup::Id
#-------------------------------------------


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# PUBLIC EC2 DEFINITION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Public EC2 Instance
#-------------------------------------------
  PublicEC2Instance:
    Type: AWS::EC2::Instance
#.............................
    CreationPolicy:
      ResourceSignal:    
        Count: 1
        Timeout: "PT3M"
#.............................
    Properties:
#.............................
      Tags:
        -
          Key: "Name"
          Value: "openvpn-public"
#.............................
      AvailabilityZone:
        'Fn::Select':
          - '0'
          - 'Fn::GetAZs':
              Ref: 'AWS::Region'
#.............................
      DisableApiTermination: false
      IamInstanceProfile: "dh.InstProfile.Managed.SysAdmin"
      ImageId: "ami-0d4c3eabb9e72650a"
      InstanceType: "t2.micro"
      KeyName: !Sub "dh.SSH.Default_${AWS::Region}"
      Monitoring: false
#      SubnetId:
#        Ref: PublicSubnetIdA
#      SecurityGroupIds:
#        - !Ref PublicSgResourceId
#.............................
      BlockDeviceMappings: 
      - 
        DeviceName: "/dev/xvda"
        Ebs: 
          Encrypted: true
          VolumeSize: 8
          VolumeType: "gp2"
          DeleteOnTermination: true
#.............................
      NetworkInterfaces: 
      - 
        Description: "Primary Public NIC"
        DeleteOnTermination: true
        DeviceIndex: 0
        PrivateIpAddress: 10.0.128.10
        SubnetId: !Ref PublicSubnetIdA
        GroupSet: 
          - !Ref PublicSgResourceId
#.............................
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            # Update Packages, inc. aws-cfn-bootstrap
            yum update -y
            # Start cfn-init
            /opt/aws/bin/cfn-init -v --configsets Step1 --stack ${AWS::StackId} --resource PublicEC2Instance --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
            # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
            #/opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
            # All done so signal success
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource PublicEC2Instance --region ${AWS::Region}
#.............................
    Metadata:
      Comment: Metadata description here.
#,,,,,,,,,,,,,,
      AWS::CloudFormation::Authentication: 
        rolebased: 
          type: "S3"
          buckets: 
            - "dh.scripts"
          roleName: "dh.InstProfile.Managed.SysAdmin"
#,,,,,,,,,,,,,,
      AWS::CloudFormation::Init:
        configSets:
          Step1:
            - configWebServer
            - configIPtables
            - configLogs
            - configRepo
#            - configHardenSsh
#            - configOpenvpn
#,,,,,,,,,,,,,,
#        configTemplate:
#          packages: {}
#          groups: {}
#          users: {}
#          sources: {}
#          files: {}
#          commands: {}
#          services: {}
#,,,,,,,,,,,,,,
        configRepo:
          commands:
            epel:
              command: "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
#,,,,,,,,,,,,,,
        configWebServer:
          packages:
            yum:
              httpd: []
          files:
            "/var/www/html/index.html":
              content: !Sub |
                <h1>Hello from ${AWS::StackId}<h1>
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              httpd:
                enabled: true
                ensureRunning: true
#,,,,,,,,,,,,,,
        configIPtables:
          packages:
            yum:
              iptables-services: []
          sources:
            /tmp: "https://s3.eu-central-1.amazonaws.com/dh.scripts/iptables/dh.cform.openvpn-ec2-pub-iptables.sh.tar.gz"
          commands:
            iptables:
              cwd: "/tmp"
              command: "/bin/bash dh.cform.openvpn-ec2-pub-iptables.sh"
          services:
              iptables:
                enables: true
                ensureRunning: true
#,,,,,,,,,,,,,,
        configLogs:
          files:
#---------------------------
            "/etc/rsyslog.d/30-iptables.conf":
              content: |
                :msg, startswith, "IPTlog" -/var/log/dh.vpn.svr.iptables.log
                & stop
              mode: '000644'
              owner: root
              group: root
#---------------------------
            "/etc/logrotate.d/dh.vpnlogs":
              content: |
                /var/log/dh.vpn.svr.*.log
                {
                 notifempty
                 rotate 21
                 maxsize 500k
                 daily
                 maxage 7
                 copytruncate
                 dateext
                 dateformat .%Y%m%d-%H-%s
                 compress
                 nomail
                 sharedscripts
                 postrotate
                   systemctl restart rsyslog.service
                 endscript
                }
              mode: '000644'
              owner: root
              group: root
#---------------------------
            "/etc/cron.d/dh.vpn.logSchedule":
              content: |
                */30 * * * * root /sbin/logrotate /etc/logrotate.d/dh.vpnlogs
              mode: '000644'
              owner: root
              group: root
#          commands:
#            rsyslog:
#              command: "systemctl restart rsyslog.service"
          services:
              rsyslog:
                enables: true
                ensureRunning: true
                files:
                  - "/etc/rsyslog.d/30-iptables.conf"
              crond:
                enable: true
                ensureRunning: true
                files:
                  - "/etc/cron.d/dh.vpn.logSchedule"


#-------------------------------------------



Outputs: {}
#Outputs:
#===========================================


#---Top Level VPCID Export
#-------------------------------------------
#  PubLaunchTmpltId:
#    Description: ID of the launch template.
#    Value:
#      Ref: PublicLaunchTemplate
#    Export:
#      Name:
#        Fn::Sub: ${AWS::StackName}-VPCID
#---Public Subnet AZ-A Export
#-------------------------------------------