AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Network Load Balancer for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------


Metadata: {}


Parameters:
#===========================================

#-------------------------------------------
#--- AWS-Specific Parameter Type
#-------------------------------------------
  VPCID:
    Description: VPC to associate with load balancer 
    Type: AWS::EC2::VPC::Id
#-------------------------------------------
  PublicSubnetIdA:
    Description: Public Subnet ID AZ-A
    Type: AWS::EC2::Subnet::Id
#-------------------------------------------
  PublicSubnetIdB:
    Description: Public Subnet ID AZ-B
    Type: AWS::EC2::Subnet::Id
#-------------------------------------------
  TargetGroupArnNLB:
    Description: Network Loadbalancer Target Group ARN
    Type: String
#-------------------------------------------


Conditions: {}


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# NETWORK LOAD BALANCER DEFINITIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Load Balancer Definition
#-------------------------------------------
  OpenvpnLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
#.............................
    Properties:
#.............................
      Name: !Sub "ovpn-nlb-${AWS::Region}"
#.............................
      Tags:
        - 
          Key: "Name"
          Value: "OpenvpnLoadBalancer"
#.............................
      Type: "network"
      Scheme: "internet-facing"
      IpAddressType: "ipv4"
#.............................
      Subnets:
        - !Ref PublicSubnetIdA
        - !Ref PublicSubnetIdB
#.............................
      LoadBalancerAttributes: 
        - 
          Key: "access_logs.s3.enabled"
          Value: "false"
        - 
          Key: "load_balancing.cross_zone.enabled"
          Value: "true"
        - 
          Key: "deletion_protection.enabled"
          Value: "false"
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#--- Load Balancer Listener Definition
#-------------------------------------------
  OpenvpnLoadBalancerListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
#.............................
    Properties:
#.............................
      Protocol: "TCP_UDP"
      Port: 1194
      LoadBalancerArn: !Ref OpenvpnLoadBalancer
#.............................
      DefaultActions: 
        - 
          TargetGroupArn: !Ref TargetGroupArnNLB
          Type: "forward"
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#-------------------------------------------



#Outputs: {}
Outputs:
#===========================================


#--- EC2 Load Balancer ARN
#-------------------------------------------
  OpenvpnLoadBalancerARN:
    Description: Network Loadbalancer ARN
    Value: !Ref OpenvpnLoadBalancer
#-------------------------------------------
#--- EC2 Load Balancer Name
#-------------------------------------------
  OpenvpnLoadBalancerName:
    Description: Network Loadbalancer Name
    Value: !GetAtt OpenvpnLoadBalancer.LoadBalancerName
#-------------------------------------------