---
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Auto Scale Group EC2 Server for OpenVPN Implementation.
  A Nested Stack that comprises:
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
# ------------------------------------------


# ==========================================
Metadata: {}
# Metadata:


# ==========================================
# Parameters {}
Parameters:

  # ------------------------------------------
  # --- The Project Name
  ProjectName:
    Description: "Name of this Openvpn project"
    ConstraintDescription: "Specify name of the project"
    Type: String
    Default: "dh-openvpn"
    MinLength: 3
    MaxLength: 63
    AllowedPattern:
      (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

  # ------------------------------------------
  # --- Public Subnet IDs
  PublicSubnetIdA:
    Description: "Public Subnet ID AZ-A"
    Type: "AWS::EC2::Subnet::Id"
  # .............................
  PublicSubnetIdB:
    Description: "Public Subnet ID AZ-B"
    Type: "AWS::EC2::Subnet::Id"

  # ------------------------------------------
  LaunchTemplateIdASG:
    Description: "Launch Template Id AutoScalingGroup"
    Type: String
  # ------------------------------------------
  TargetGroupArnNLB:
    Description: "Network Loadbalancer Target Group ARN"
    Type: String
  # ------------------------------------------
  OpenvpnSNSTopicARN:
    Description: "Openvpn SNS Activity Topic ARN"
    Type: String


# ==========================================
Conditions: {}
# Conditions:


# ==========================================
Resources:

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #       AUTO SCALE GROUP DEFINITION
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  # ------------------------------------------
  # --- Auto Scale Group
  OpenvpnEC2AutoScaleGrp:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    # .............................
    Properties:
      # .............................
      AutoScalingGroupName: !Sub "${ProjectName}-autoscale-group"
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateIdASG
        Version: "1"
      # .............................
      Tags:
        -
          Key: "Name"
          Value: !Sub "${ProjectName}-autoscale-grp"
          PropagateAtLaunch: true
      # .............................
      VPCZoneIdentifier:
        - !Ref PublicSubnetIdA
        - !Ref PublicSubnetIdB
      # .............................
      Cooldown: "210"
      DesiredCapacity: "1"
      MinSize: "1"
      MaxSize: "1"
      # .............................
      HealthCheckType: "ELB"
      HealthCheckGracePeriod: 180
      # .............................
      TargetGroupARNs:
        - !Ref TargetGroupArnNLB
      # .............................
      MetricsCollection:
        - Granularity: "1Minute"
          Metrics:
            - "GroupInServiceInstances"
            - "GroupTotalInstances"
      # .............................
      NotificationConfigurations:
        - NotificationTypes:
            - autoscaling:EC2_INSTANCE_LAUNCH
            - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
            - autoscaling:EC2_INSTANCE_TERMINATE
            - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
            - autoscaling:TEST_NOTIFICATION
          TopicARN: !Ref OpenvpnSNSTopicARN


# ==========================================
Outputs: {}
# Outputs:
