AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Simple Notification Service for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------


Metadata: {}


#Parameters: {}
Parameters:
#===========================================

#--- The Project Name
#-------------------------------------------
  ProjectName:
    Description: Name of this Openvpn project.
    ConstraintDescription: Specify name of the project.
    Type: String
    Default: "dh-openvpn"
    MinLength: 3
    MaxLength: 63
    AllowedPattern: (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

#-------------------------------------------
  OpenvpnSubsEmailSNS:
    Description: Openvpn SNS Email Endpoint
    Type: String
#-------------------------------------------


Conditions: {}


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SNS NOTIFICATIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- SNS Topic Definition
#-------------------------------------------
  OpenvpnTopicSNS:
    Type: "AWS::SNS::Topic"
#.............................
    Properties:
      DisplayName: "OpenvpnNotice"
      TopicName: !Sub "${ProjectName}-activity-notice-${AWS::Region}"
#.............................
      Tags: 
      - 
        Key: "Name"
        Value: "openvpn-activity-sns"
#.............................
#      KmsMasterKeyId: "alias/aws/sns"
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#--- SNS Subscription Definition
#-------------------------------------------
  OpenvpnSubscriptionSNS:
    Type: "AWS::SNS::Subscription"
#.............................
    Properties:
      TopicArn: !Ref OpenvpnTopicSNS
      Endpoint: !Ref OpenvpnSubsEmailSNS
      Protocol: "email"
      Region: !Ref AWS::Region
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#-------------------------------------------


#Outputs: {}
Outputs:
#===========================================


#--- SNS Topic ARN
#-------------------------------------------
  OpenvpnSNSTopicARN:
    Description: "Openvpn SNS Activity Topic ARN"
    Value: !Ref OpenvpnTopicSNS
#-------------------------------------------