AWSTemplateFormatVersion: '2010-09-09'
Description: >
  An OpenVPN implementation that comprises:
  Highly Available EC2 Instance bla bla.
  Autoscaling Group bla bla.
  Isolated Certificate Authority bla bla.
  Nested Stack as follows:
  Bla Bla.
  Inputs:
  Bla Bla.
  Outputs.
  Bla Bla.
#-------------------------------------------


Metadata: {}
#===========================================


Parameters:
#===========================================

#--- The Project Name
#-------------------------------------------
  ProjectName:
    Description: Name of this Openvpn project.
    ConstraintDescription: Specify name of the project.
    Type: String
    Default: "dh-openvpn"
    MinLength: 3
    MaxLength: 63
    AllowedPattern: (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

#--- Script Build Stage Counter
#-------------------------------------------
  BuildStage: 
    Description: Shell script Stage counter.
    ConstraintDescription: Must be > 0 & < 3.
    Type: String
    Default: Stage0
    AllowedValues: 
      - Stage0
      - Stage1
      - Stage2
      - Stage3

#--- Latest Amazon_Linux_2 AMI
#-------------------------------------------
#   (Value retrived via shell scrip)
  CurrentAmi:
    Description: The AMI to use for EC2 instances.
    Type: AWS::EC2::Image::Id
# SSM method below but variable type not versatile to scripts. 
#  myAmi:
#    Description: The AMI to use for EC2 instances.
#    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
#    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

#--- SNS Email Notifications
#-------------------------------------------
  OpenvpnSubsEmailSNS:
    Description: Openvpn SNS Email Endpoint.
    ConstraintDescription: Must be a valid email address.
    Type: String
    Default: "dh.info@posteo.net"
    AllowedPattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$
#-------------------------------------------


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SUBNET CIDR DEFINITIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#--- AZ-A Public Subnet
#-------------------------------------------
# Public Subnet A CIDR : 10.0.128.0/20

#--- AZ-B Public Subnet
#-------------------------------------------
# Public Subnet B CIDR : 10.0.144.0/20

#--- AZ-A Private Subnet
#-------------------------------------------
# Public Subnet A CIDR : 10.0.0.0/19

#--- AZ-B Private Subnet
#-------------------------------------------
# Public Subnet B CIDR : 10.0.32.0/19

#-------------------------------------------


#Conditions: {}
Conditions:
#===========================================  
  CreateResourcesStage0: !Equals [ !Ref BuildStage, Stage0]
  CreateResourcesStage1: !Equals [ !Ref BuildStage, Stage1]
  CreateResourcesStage2: !Equals [ !Ref BuildStage, Stage2]
  CreateResourcesStage3: !Equals [ !Ref BuildStage, Stage3]


Resources:
#===========================================

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# NESTED STACKS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- VPC Definition
#-------------------------------------------
  VPCDef:
    Type: AWS::CloudFormation::Stack
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.vpc.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        BuildStage:
          !Ref BuildStage
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Public/Private NACLs
#-------------------------------------------
  NaclDefs:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCDef
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.vpc-nacl.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSubnetIdB:
          !GetAtt VPCDef.Outputs.PublicSubnetIdB
        PrivateSubnetIdA:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdA
        PrivateSubnetIdB:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdB
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Public/Private Security Groups
#-------------------------------------------
  SgDefs:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCDef
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.vpc-sg.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
#        ApplicationName:
#          Ref: AWS::StackName
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Private/Public EC2 Instances
#-------------------------------------------
  InstancePubDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage1
    DependsOn: VPCDef
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.ec2-pub.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        ProjectName:
          !Ref ProjectName
        PublicAmiId:
          !Ref CurrentAmi
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 10
#-------------------------------------------
  InstancePrivDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage1
    DependsOn: InstancePubDef
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.ec2-priv.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        ProjectName:
          !Ref ProjectName
        PrivateAmiId:
          !Ref CurrentAmi
        PrivateSubnetIdA:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdA
        PrivateSgResourceId:
          !GetAtt SgDefs.Outputs.PrivateSgResourceId
      TimeoutInMinutes: 10
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- EC2 Launch Template
#-------------------------------------------
  LaunchTemplateDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.ec2-lt.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        ProjectName:
          !Ref ProjectName
        PublicLtAmiId:
          !Ref CurrentAmi
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- EC2 Target Group
#-------------------------------------------
  TargetGroupDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.ec2-tg.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- SNS Topic
#-------------------------------------------
  OpenvpnSNSTopicDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.sns.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        OpenvpnSubsEmailSNS:
          !Ref OpenvpnSubsEmailSNS
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- EC2 AutoScaling Group
#-------------------------------------------
  AutoScaleGroupDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    DependsOn: 
      - LaunchTemplateDef
      - TargetGroupDef
      - OpenvpnSNSTopicDef
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.ec2-asg.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSubnetIdB:
          !GetAtt VPCDef.Outputs.PublicSubnetIdB
        LaunchTemplateIdASG:
          !GetAtt LaunchTemplateDef.Outputs.LaunchTemplateId
        TargetGroupArnNLB:
          !GetAtt TargetGroupDef.Outputs.OpenvpnTargetGroupARN
        OpenvpnSNSTopicARN:
          !GetAtt OpenvpnSNSTopicDef.Outputs.OpenvpnSNSTopicARN
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- EC2 Network Load Balancer 
#-------------------------------------------
  NetworkLoadBalancerDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    DependsOn: AutoScaleGroupDef
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.ec2-nlb.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSubnetIdB:
          !GetAtt VPCDef.Outputs.PublicSubnetIdB
        TargetGroupArnNLB:
          !GetAtt TargetGroupDef.Outputs.OpenvpnTargetGroupARN
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- CloudWatch Alarm 
#-------------------------------------------
  OpenvpnCloudWatchAlarmDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    DependsOn: 
      - NetworkLoadBalancerDef
      - TargetGroupDef
      - OpenvpnSNSTopicDef
    Properties:
#,,,,,,,,,,,,,,,,
      TemplateURL:
        !Join
          - ""
          - - "https://"
            - !Ref ProjectName
            - ".s3."
            - !Ref "AWS::Region"
            - ".amazonaws.com/"
            - "cfn-templates/dh-openvpn-cfn.cw.yaml"
#,,,,,,,,,,,,,,,,
      Parameters:
        OpenvpnSNSTopicARN:
          !GetAtt OpenvpnSNSTopicDef.Outputs.OpenvpnSNSTopicARN
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#-------------------------------------------


#Outputs: {}
Outputs:
#===========================================

#--- Instance IDs
#-------------------------------------------
  InstanceIdPublic1:
    Description:  Public Instance ID
    Condition: CreateResourcesStage1
    Value:
      !GetAtt InstancePubDef.Outputs.Pub1EC2InstanceId
#-------------------------------------------
  InstanceIdPrivate:
    Description: Private Instance ID
    Condition: CreateResourcesStage1
    Value:
      !GetAtt InstancePrivDef.Outputs.PrivEC2InstanceId
#-------------------------------------------
#  ExportsStackName:
#    Value: !Ref 'AWS::StackName'
#    Export:
#      Name: !Sub 'ExportsStackName-${AWS::StackName}'

