AWSTemplateFormatVersion: '2010-09-09'
Description: >
  DNS Record Set for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------


Metadata: {}


Parameters:
#===========================================

#-------------------------------------------
#--- Route53 Particulars
#-------------------------------------------
  OpenvpnDomainName:
    Description: OpenVPN Domain Name 
    Type: String
    Default: "cloudemprise.net"
    AllowedPattern: ^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})$
#-------------------------------------------
  OpenvpnR53HostedZoneId:
    Description: An Amazon Route 53 hosted zone ID 
    Type: AWS::Route53::HostedZone::Id
#-------------------------------------------
  OpenvpnLoadBalancerDNS:
    Description: OpenVPN Network Loadbalancer DNS 
    Type: String
#-------------------------------------------
  OpenvpnLoadBalancerZoneId:
    Description: Network Loadbalancer Hosted Zone ID 
    Type: String
#-------------------------------------------



Conditions: {}


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ROUTE 53 RECORD SET
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Record Set Definition
#-------------------------------------------
  OpenvpnR53RecordSet:
    Type: "AWS::Route53::RecordSet"
#.............................
    Properties:
#.............................
      Name: !Sub "vpn.${OpenvpnDomainName}"
      Comment: "Openvpn Route53 Record Set"
#.............................
      Type: "A"
      HostedZoneId: !Ref OpenvpnR53HostedZoneId
#.............................
      AliasTarget: 
        HostedZoneId: !Ref OpenvpnLoadBalancerZoneId
        DNSName: !Ref OpenvpnLoadBalancerDNS
        EvaluateTargetHealth: true
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#-------------------------------------------



Outputs: {}
#Outputs:
#===========================================


#--- EC2 Load Balancer ARN
#-------------------------------------------
#  OpenvpnLoadBalancerARN:
#    Description: Network Loadbalancer ARN
#    Value: !Ref OpenvpnLoadBalancer
#-------------------------------------------
#--- EC2 Load Balancer Name
#-------------------------------------------
#  OpenvpnLoadBalancerName:
#    Description: Network Loadbalancer Name
#    Value: !GetAtt OpenvpnLoadBalancer.LoadBalancerName
#-------------------------------------------