AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch Template EC2 Server for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------


Metadata: {}


Parameters:
#===========================================

#--- The Project Name
#-------------------------------------------
  ProjectName:
    Description: Name of this Openvpn project.
    ConstraintDescription: Specify name of the project.
    Type: String
    Default: "dh-openvpn"
    MinLength: 3
    MaxLength: 63
    AllowedPattern: (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

#--- AMI for EC2 instance
#-------------------------------------------
  PublicLtAmiId:
    Description: Launc Template Public AMI ID 
    Type: AWS::EC2::Image::Id
#-------------------------------------------

#--- Public Security Group Resource ID
#-------------------------------------------
  PublicSgResourceId:
    Description: Public Security Group ID AZ-A
    Type: AWS::EC2::SecurityGroup::Id
#-------------------------------------------


Conditions: {}


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# LAUNCH TEMPLATE EC2 DEFINITION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Public EC2 Launch Template
#-------------------------------------------
  PublicEC2LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Description: "Openvpn Launch Template for AutoScaling"
#.............................
    Properties:
      LaunchTemplateName: "openvpn-launch-template"
#.............................
      LaunchTemplateData:
        ImageId: !Ref PublicLtAmiId
        InstanceType: "t2.nano"
        KeyName: !Sub "dh.ec2.ssh.admin.console_${AWS::Region}"
        Monitoring:
          Enabled: false
        SecurityGroupIds:
          - !Ref PublicSgResourceId
#.............................
        IamInstanceProfile: 
          Name: "dh.instprofile.managed.sysadmin"
#.............................
        UserData:
          Fn::Base64: 
            !Sub |
              #!/bin/bash -xe
              # Download Server Certs & start Openvpn dual-protocol service
              aws s3 sync s3://${ProjectName}/easy-rsa/issued-certs/ /tmp --exclude "*" --include "*.server.tar.gz"
              tar -xzf /tmp/*.server.tar.gz -C /etc/openvpn/server/
              rm /tmp/*.server.tar.gz
              systemctl enable openvpn-server@dh.vpn.server.udp1194
              systemctl enable openvpn-server@dh.vpn.server.tcp1194
              systemctl start openvpn-server@dh.vpn.server.udp1194
              systemctl start openvpn-server@dh.vpn.server.tcp1194
              # Health Checks facilitated by httpd Port 80
              systemctl enable httpd
              systemctl start httpd
#.............................
        TagSpecifications:
          -
            ResourceType: "instance"
            Tags:
              -
                Key: "Name"
                Value: "openvpn-autoscaled"
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#-------------------------------------------



#Outputs: {}
Outputs:
#===========================================


#--- Public Instance ID
#-------------------------------------------
  LaunchTemplateId:
    Description: Launch Template ID
    Value:
      Ref: PublicEC2LaunchTemplate
#-------------------------------------------