#https://s3.eu-central-1.amazonaws.com/dh.cfn-templates/openvpn/dh.cform.openvpn-ec2-asg.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Auto Scale Group EC2 Server for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------


Metadata: {}


Parameters:
#===========================================

#--- Public Subnet IDs
#-------------------------------------------
  PublicSubnetIdA:
    Description: Public Subnet ID AZ-A
    Type: AWS::EC2::Subnet::Id
#-------------------------------------------
  PublicSubnetIdB:
    Description: Public Subnet ID AZ-B
    Type: AWS::EC2::Subnet::Id
#-------------------------------------------
  LaunchTemplateIdASG:
    Description: Launch Template Id AutoScalingGroup
    Type: String
#-------------------------------------------
#  LaunchTemplateVersion:
#    Description: Launch Template Version Number
#    Type: String
#-------------------------------------------
  TargetGroupArnNLB:
    Description: Network Loadbalancer Target Group ARN
    Type: String
#-------------------------------------------
  OpenvpnSNSTopicARN:
    Description: "Openvpn SNS Activity Topic ARN"
    Type: String
#-------------------------------------------


Conditions: {}


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# AUTO SCALE GROUP EC2 DEFINITION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Auto Scale Group 
#-------------------------------------------
  OpenvpnEC2AutoScaleGrp:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Description: "This is the launch template description"
#.............................
    Properties:
      AutoScalingGroupName: "openvpn-autoscaling-group"
#.............................
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplateIdASG
        Version: 1
#        Version: !Ref LaunchTemplateVersion
#        LaunchTemplateName: "openvpn-launch-template"
#.............................
      Tags:
        - 
          Key: "Name"
          Value: "openvpn-autoscale-grp"
          PropagateAtLaunch: true
#.............................
      VPCZoneIdentifier:
        - !Ref PublicSubnetIdA
        - !Ref PublicSubnetIdB
#.............................
      Cooldown: 210
      DesiredCapacity: 1
      MinSize: 1
      MaxSize: 1
#.............................
      HealthCheckType: "ELB"
      HealthCheckGracePeriod: 180
#.............................
      TargetGroupARNs:
        - !Ref TargetGroupArnNLB
#.............................
      MetricsCollection: 
        - Granularity: "1Minute"
          Metrics: 
            - "GroupInServiceInstances"
            - "GroupTotalInstances"
#.............................
      NotificationConfigurations:
        - NotificationTypes:
          - autoscaling:EC2_INSTANCE_LAUNCH
          - autoscaling:EC2_INSTANCE_LAUNCH_ERROR
          - autoscaling:EC2_INSTANCE_TERMINATE
          - autoscaling:EC2_INSTANCE_TERMINATE_ERROR
          - autoscaling:TEST_NOTIFICATION
          TopicARN: !Ref OpenvpnSNSTopicARN
#.............................
#      TerminationPolicies: 
#        - "Default"
#      ServiceLinkedRoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
#.............................
#      MaxInstanceLifetime: 604800
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#-------------------------------------------



Outputs: {}
#Outputs:
#===========================================


#--- Public Instance ID
#-------------------------------------------
#  OpenvpnAutoScaleGroupName:
#    Description: AutoScaling Group Name
#    Value: !GetAtt OpenvpnEC2AutoScaleGrp.TargetGroupName
#-------------------------------------------