AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch Template EC2 Server for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------


Metadata: {}


#Parameters: {}
Parameters:
#===========================================

#--- The Project Name
#-------------------------------------------
  ProjectName:
    Description: Name of this Openvpn project.
    ConstraintDescription: Specify name of the project.
    Type: String
    Default: "dh-openvpn"
    MinLength: 3
    MaxLength: 63
    AllowedPattern: (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$(?<!\-))

#--- AMI for EC2 instance
#-------------------------------------------
  PublicAmiId:
    Description: Public AMI ID
    Type: AWS::EC2::Image::Id
#-------------------------------------------

#--- Public Subnet ID
#-------------------------------------------
  PublicSubnetIdA:
    Description: Public Subnet ID AZ-A
    Type: AWS::EC2::Subnet::Id
#-------------------------------------------

#--- Public Security Group Resource ID
#-------------------------------------------
  PublicSgResourceId:
    Description: Public Security Group ID AZ-A
    Type: AWS::EC2::SecurityGroup::Id
#-------------------------------------------

#--- EC2 Instance Profile ARN
#-------------------------------------------
#  InstanceProfileARN:
#    Description: Openvpn EC2 Instance Profile ARN
#    Type: String
#-------------------------------------------


Conditions: {}


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# PUBLIC EC2 DEFINITION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Public EC2 Instance
#-------------------------------------------
  PublicEC2Instance:
    Type: AWS::EC2::Instance
#.............................
    CreationPolicy:
      ResourceSignal:    
        Count: 1
        Timeout: "PT10M"
#.............................
    Properties:
#.............................
      Tags:
        -
          Key: "Name"
          Value: "openvpn-public"
#.............................
      AvailabilityZone:
        'Fn::Select':
          - '0'
          - 'Fn::GetAZs':
              Ref: 'AWS::Region'
#.............................
      DisableApiTermination: false
#      IamInstanceProfile: "dh-openvpn-server-restrictive"
      IamInstanceProfile: !Sub "${ProjectName}-instance-profile-${AWS::Region}"
      ImageId: !Ref PublicAmiId
      InstanceType: "t2.nano"
      KeyName: !Sub "dh.ec2.ssh.admin.console_${AWS::Region}"
      Monitoring: false
#      SubnetId:
#        Ref: PublicSubnetIdA
#      SecurityGroupIds:
#        - !Ref PublicSgResourceId
#.............................
      BlockDeviceMappings: 
      - 
        DeviceName: "/dev/xvda"
        Ebs: 
          Encrypted: true
          VolumeSize: 8
          VolumeType: "gp2"
          DeleteOnTermination: true
#.............................
      NetworkInterfaces: 
      - 
        Description: "Primary Public NIC"
        DeleteOnTermination: true
        DeviceIndex: 0
        PrivateIpAddress: 10.0.128.10
        SubnetId: !Ref PublicSubnetIdA
        GroupSet: 
          - !Ref PublicSgResourceId
#.............................
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            # Update Packages, inc. aws-cfn-bootstrap
            yum update -y
            # Fix openssl error (easy-rsa) : random seed file 
            export RANDFILE=/tmp/.rnd 
            # Start cfn-init
            /opt/aws/bin/cfn-init -v --configsets Step1 --stack ${AWS::StackId} --resource PublicEC2Instance --region ${AWS::Region} || error_exit 'Failed to run cfn-init'
            # Start up the cfn-hup daemon to listen for changes to the EC2 instance metadata
            #/opt/aws/bin/cfn-hup || error_exit 'Failed to start cfn-hup'
            # All done so signal success
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource PublicEC2Instance --region ${AWS::Region}
#.............................
    Metadata:
      Comment: Metadata description here.
#,,,,,,,,,,,,,,
      AWS::CloudFormation::Authentication: 
        rolebased: 
          type: "S3"
          buckets: 
            - !Ref ProjectName
#          roleName: "dh-openvpn-server-restrictive"
          roleName: !Sub "${ProjectName}-iam-role-${AWS::Region}"

#,,,,,,,,,,,,,,
      AWS::CloudFormation::Init:
        configSets:
          Step1:
            - configMisc
            - configRepo
            - configYum
            - configHardenSsh
            - configIPtables
            - configLogs
            - configWebServer
            - configEasyRSA
            - configOpenvpn

#,,,,,,,,,,,,,,,,,,,,,,,,,,,,
#        configTemplate:
#          packages: {}
#          groups: {}
#          users: {}
#          sources: {}
#          files: {}
#          commands: {}
#          services: {}
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


        configMisc:
          commands:
            1_dhcpv6:
              command: "sed -i 's/DHCPV6C=yes/DHCPV6C=no/' /etc/sysconfig/network-scripts/ifcfg-eth0"
            2_timePool:
              command: "sed -i 's/^pool/#&/' /etc/chrony.conf"
            3_persistLogs:
              command: "sed -i 's/.*Storage.*/Storage=persistent/' /etc/systemd/journald.conf"
          services:
            sysvinit:
              network:
                ensureRunning: "true"
                enabled: "true"
                commands:
                  - "1_dhcpv6"
              chronyd:
                ensureRunning: "true"
                enabled: "true"
                commands:
                  - "2_timePool"
              systemd-journald:
                ensureRunning: "true"
                enabled: "true"
                commands:
                  - "3_persistLogs"


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,        
        configRepo:
          packages:
            rpm:
              epel: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
          commands:
            1a_epel:
              command: "yum-config-manager --enable epel"
            1b_epel:
              command: 'sed -i "/\[epel\]/a priority=20" /etc/yum.repos.d/epel.repo'


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,        
        configYum:
          packages:
            yum:
              yum-cron: []
          commands:
            1a_yumCron:
              command: "sed -i 's/.*update_cmd.*/update_cmd = security/' /etc/yum/yum-cron.conf"
            1b_yumCron:
              command: "sed -i 's/.*apply_updates.*/apply_updates = yes/' /etc/yum/yum-cron.conf"
          services:
            sysvinit:
              yum-cron:
                ensureRunning: "true"
                enabled: "true"
                commands:
                  - "1b_yumCron"


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        configHardenSsh:
          packages:
            yum:
              fail2ban: []
          sources:
            /tmp: 
              !Join
                - ""
                - - "https://"
                  - !Ref ProjectName
                  - ".s3."
                  - !Ref "AWS::Region"
                  - ".amazonaws.com/"
                  - "ssh/dh-openvpn-ec2-harden-ssh.sh.tar.gz"
          files:
            "/etc/fail2ban/jail.local":
              content: |
                [sshd]
                enabled = true
                ignoreip = 127.0.0.1/8
                bantime = 600
                findtime = 600
                maxretry = 3
                mode = aggressive
                banaction = iptables-multiport
              mode: '000644'
              owner: root
              group: root
          commands:
            HardenF2B:
              cwd: "/etc/fail2ban/jail.d"
              command: "mv 00-firewalld.conf 00-firewalld.disable"
            HardenSsh:
              cwd: "/tmp/ssh"
              command: "./dh-openvpn-ec2-harden-ssh.sh"
          services:
            sysvinit:
              firewalld:
                ensureRunning: "false"
                enabled: "false"
              fail2ban: 
                enabled: "true"
                ensureRunning: "true"
                files:
                  - "/etc/fail2ban/jail.local"
                commands: 
                  - "HardenF2B"
              sshd:
                enabled: "true"
                ensureRunning: "true"
                commands:
                  - "HardenSsh"


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        configIPtables:
          packages:
            yum:
              iptables-services: []
          sources:
            /tmp:
              !Join
                - ""
                - - "https://"
                  - !Ref ProjectName
                  - ".s3."
                  - !Ref "AWS::Region"
                  - ".amazonaws.com/"
                  - "iptables/dh-openvpn-ec2-pub-iptables.sh.tar.gz"
          files:
            "/etc/sysctl.d/30-dh-openvpn-iptables.conf":
              content: |
                net.ipv4.ip_forward = 1
                net.ipv6.conf.default.disable_ipv6 = 1
                net.ipv6.conf.all.disable_ipv6 = 1
                kernel.randomize_va_space = 1
                net.ipv4.conf.default.rp_filter = 1
                net.ipv4.conf.all.rp_filter = 1
                net.ipv4.tcp_syncookies = 1
              mode: '000644'
              owner: root
              group: root
          commands:
            1_kernelParams:
              command: "sysctl -p /etc/sysctl.d/30-dh-openvpn-iptables.conf"
            2_iptRules:
              cwd: "/tmp/iptables"
              command: "./dh-openvpn-ec2-pub-iptables.sh"
          services:
            sysvinit:
              iptables:
                ensureRunning: "true"
                enabled: "true"
                commands:
                  - "2_iptRules"


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        configLogs:
          files:
#---------------------------
            "/etc/rsyslog.d/30-iptables.conf":
              content: |
                :msg, startswith, "IPTlog" -/var/log/dh-openvpn-server-iptables.log
                & stop
              mode: '000644'
              owner: root
              group: root
#---------------------------
            "/etc/logrotate.d/dh-openvpn-logs":
              content: |
                /var/log/dh-openvpn-server-*.log
                {
                 notifempty
                 rotate 21
                 maxsize 500k
                 daily
                 maxage 7
                 copytruncate
                 dateext
                 dateformat .%Y%m%d-%H-%s
                 compress
                 nomail
                 sharedscripts
                 postrotate
                   systemctl restart rsyslog.service
                 endscript
                }
              mode: '000644'
              owner: root
              group: root
#---------------------------
            "/etc/cron.d/dh-openvpn-logs-schedule":
              content: |
                */30 * * * * root /sbin/logrotate /etc/logrotate.d/dh-openvpn-logs
              mode: '000644'
              owner: root
              group: root
          services:
            sysvinit:
              rsyslog:
                ensureRunning: "true"
                enabled: "true"
                files:
                  - "/etc/rsyslog.d/30-iptables.conf"


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,
# For use: Network LoadBalancer HealthChecks
        configWebServer:
          packages:
            yum:
              httpd: []
          files:
            "/var/www/html/index.html":
              content: !Sub |
                <h1>Hello from ${AWS::StackId}<h1>
              mode: '000644'
              owner: root
              group: root
# Service enabled within Autoscaling Launch Template 
# UserData to facilitate validation.
#          services:
#            sysvinit:
#              httpd:
#                enabled: "true"
#                ensureRunning: "true"
#                files:
#                  - "/var/www/html/index.html"


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        configEasyRSA:
          packages:
            yum:
              easy-rsa: []
          files:
            "/usr/local/easy-rsa/vars":
              content: |
                set_var EASYRSA_REQ_CN "none"
                set_var EASYRSA_BATCH "yes"
                set_var EASYRSA_ALGO ec
                set_var EASYRSA_CURVE secp521r1
                set_var EASYRSA_KEY_SIZE 4096
                set_var EASYRSA_DIGEST "sha512"
              mode: '000644'
              owner: root
              group: root
          sources:
            /usr/local:
              !Join
                - ""
                - - "https://"
                  - !Ref ProjectName
                  - ".s3."
                  - !Ref "AWS::Region"
                  - ".amazonaws.com/"
                  - "easy-rsa/dh-openvpn-vars/dh-openvpn-easyrsa-vars.tar.gz"
          commands:
            1a_initPKI:
              command: "mkdir -p /usr/local/easy-rsa && cp -r /usr/share/easy-rsa/3/* $_"
            1b_initPKI:
              cwd: "/usr/local/easy-rsa"
              command: "./easyrsa init-pki"
            2a_genSVR:
              cwd: "/usr/local/easy-rsa"
              command: "cp ./dh-openvpn-vars/vars_dh-openvpn-server ./vars"
            2b_genSVR:
              cwd: "/usr/local/easy-rsa"
              command: "./easyrsa gen-req dh-openvpn-server nopass"
            3a_genClient1:
              cwd: "/usr/local/easy-rsa"
              command: "cp ./dh-openvpn-vars/vars_pfSense-bmetal-client ./vars"
            3b_genClient1:
              cwd: "/usr/local/easy-rsa"
              command: "./easyrsa gen-req pfSense-bmetal-client nopass"
            4a_genClient2:
              cwd: "/usr/local/easy-rsa"
              command: "cp ./dh-openvpn-vars/vars_pfSense-virt-client ./vars"
            4b_genClient2:
              cwd: "/usr/local/easy-rsa"
              command: "./easyrsa gen-req pfSense-virt-client nopass"
            5a_genClient3:
              cwd: "/usr/local/easy-rsa"
              command: "cp ./dh-openvpn-vars/vars_android-bmetal-client ./vars"
            5b_genClient3:
              cwd: "/usr/local/easy-rsa"
              command: "./easyrsa gen-req android-bmetal-client nopass"
            6a_genClient3:
              cwd: "/usr/local/easy-rsa"
              command: "cp ./dh-openvpn-vars/vars_android-virt-client ./vars"
            6b_genClient3:
              cwd: "/usr/local/easy-rsa"
              command: "./easyrsa gen-req android-virt-client nopass"
            7a_genDH:
              cwd: "/usr/local/easy-rsa"
              command: "cp ./dh-openvpn-vars/vars_gen-dh ./vars"
            7b_genDH:
              cwd: "/usr/local/easy-rsa"
              command: "./easyrsa gen-dh"
            8a_mvKeys:
              cwd: "/usr/local/easy-rsa/pki/private"
              command: 
                !Sub "tar -zcf - *client.key | aws s3 cp - s3://${ProjectName}/openvpn/client/key/dh-openvpn-client-key.tar.gz"
            9a_mvReqs:
              cwd: "/usr/local/easy-rsa/pki/reqs"
              command: 
                !Sub "tar -zcf - *.req | aws s3 cp - s3://${ProjectName}/easy-rsa/sign-reqs/dh-openvpn-easyrsa-sign-reqs.tar.gz"


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,
        configOpenvpn:
          packages:
            yum:
              openvpn: []
          sources:
            /etc/openvpn/server:
              !Join
                - ""
                - - "https://"
                  - !Ref ProjectName
                  - ".s3."
                  - !Ref "AWS::Region"
                  - ".amazonaws.com/"
                  - "openvpn/server/conf/dh-openvpn-server-1194.conf.tar.gz"
          files:
            "/usr/local/bin/vpn-server-status":
              content: |
                #!/bin/bash
                systemctl status openvpn-server@dh-openvpn-server-udp1194
                systemctl status openvpn-server@dh-openvpn-server-tcp1194
                journalctl -u openvpn-server@dh-openvpn-server-udp1194
                journalctl -u openvpn-server@dh-openvpn-server-tcp1194
              mode: '000755'
              owner: ec2-user
              group: ec2-user
          commands:
            1a_gen-HMAC:
              cwd: "/etc/openvpn/server"
              command: "openvpn --genkey --secret hmac-sig.key"
            1b_gen-HMAC:
              cwd: "/etc/openvpn/server"
              command: 
                !Sub "tar -czf - hmac-sig.key | aws s3 cp - s3://${ProjectName}/openvpn/client/dh-openvpn-client-hmac.tar.gz"
            2a_cpSvrDH:
              cwd: "/usr/local/easy-rsa/pki"
              command: "cp dh.pem /etc/openvpn/server/"
            2b_cpSvrKey:
              cwd: "/usr/local/easy-rsa/pki/private"
              command: "cp dh-openvpn-server.key /etc/openvpn/server/"
            3_enableLogTimestamps:
              cwd: "/usr/lib/systemd/system"
              command: "cp openvpn-server@.service openvpn-server@.service.bak;sed -i 's/ --suppress-timestamps//g' openvpn-server@.service"
            4_addPATH:
              command: |
                printf '\nPATH="/usr/local/bin:$PATH"\n' >> /home/ec2-user/.bashrc
#          services:
#            sysvinit:
#              openvpn:
#                enabled: "false"
#                ensureRunning: "false"
#                files:
#                  - "/etc/openvpn/server/dh-openvpn-server-udp1194.conf"
#                  - "/etc/openvpn/server/dh-openvpn-server-tcp1194.conf"


#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#-------------------------------------------



#Outputs: {}
Outputs:
#===========================================


#--- Public Instance ID
#-------------------------------------------
  PubEC2InstanceId:
    Description: Public Instance ID
    Value:
      Ref: PublicEC2Instance
#-------------------------------------------