#https://s3.eu-central-1.amazonaws.com/dh-cfn-templates/openvpn/dh.cfn.openvpn-ec2-lt.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Launch Template EC2 Server for OpenVPN Implementation.
  A Nested Stack that comprises: 
  Bla Bla.
  Inputs include:
  Bla Bla.
  Outputs include:
  Bla Bla.
#-------------------------------------------


Metadata: {}


Parameters:
#===========================================

#--- AMI for EC2 instance
#-------------------------------------------
  PublicLtAmiId:
    Description: Launc Template Public AMI ID 
    Type: AWS::EC2::Image::Id
#-------------------------------------------

#--- Public Security Group Resource ID
#-------------------------------------------
  PublicSgResourceId:
    Description: Public Security Group ID AZ-A
    Type: AWS::EC2::SecurityGroup::Id
#-------------------------------------------


Conditions: {}


Resources:
#===========================================


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# LAUNCH TEMPLATE EC2 DEFINITION
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- Public EC2 Launch Template
#-------------------------------------------
  PublicEC2LaunchTemplate:
    Type: "AWS::EC2::LaunchTemplate"
    Description: "Openvpn Launch Template for AutoScaling"
#.............................
    Properties:
      LaunchTemplateName: "openvpn-launch-template"
#.............................
      LaunchTemplateData:
        ImageId: !Ref PublicLtAmiId
        InstanceType: "t2.nano"
#        KeyName: !Sub "dh.SSH.Default_${AWS::Region}"
        KeyName: !Sub "dh.ec2.ssh.admin.console_${AWS::Region}"
        Monitoring:
          Enabled: false
        SecurityGroupIds:
          - !Ref PublicSgResourceId
#.............................
        IamInstanceProfile: 
#          Name: "dh.InstProfile.Managed.SysAdmin"
          Name: "dh.instprofile.managed.sysadmin"
#            Arn: "arn:aws:iam::255822906044:instance-profile/dh.InstProfile.Managed.SysAdmin"
#.............................
        UserData:
          Fn::Base64: |
            #!/bin/bash -xe
            # Download Server Certs & start Openvpn dual-protocol service
            cd /etc/openvpn/server
            aws s3 sync s3://dh-scripts/easyrsa/openvpn/issued-certs/ . --exclude "*" --include "*.server.tar.gz"
            tar -xzf *.server.tar.gz
            systemctl enable openvpn-server@dh.vpn.server.udp1194
            systemctl enable openvpn-server@dh.vpn.server.tcp1194
            systemctl start openvpn-server@dh.vpn.server.udp1194
            systemctl start openvpn-server@dh.vpn.server.tcp1194
            # Health Checks facilitated by httpd Port 80
            systemctl enable httpd
            systemctl start httpd
#.............................
        TagSpecifications:
          -
            ResourceType: "instance"
            Tags:
              -
                Key: "Name"
                Value: "openvpn-autoscaled-instance"
#,,,,,,,,,,,,,,,,,,,,,,,,,,,,


#-------------------------------------------



#Outputs: {}
Outputs:
#===========================================


#--- Public Instance ID
#-------------------------------------------
  LaunchTemplateId:
    Description: Launch Template ID
    Value:
      Ref: PublicEC2LaunchTemplate
#-------------------------------------------