#https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-set1.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  An OpenVPN implementation that comprises:
  Highly Available EC2 Instance bla bla.
  Autoscaling Group bla bla.
  Isolated Certificate Authority bla bla.
  Nested Stack as follows:
  Bla Bla.
  Inputs:
  Bla Bla.
  Outputs.
  Bla Bla.
#-------------------------------------------


Metadata: {}
#===========================================


Parameters:
#===========================================

#--- Stack Build Stage Indicator
#-------------------------------------------
  BuildStage: 
    Description: Openvpn infrastructure creation comprises various stages. 
    ConstraintDescription: Specify which Stage to provision.
    Default: Stage0
    Type: String
    AllowedValues: 
      - Stage0
      - Stage1
      - Stage2
      - Stage3

#--- Latest Amazon_Linux_2 AMI 
#-------------------------------------------
  CurrentAmi:
    Description: The AMI to use for EC2 instances.
    Type: AWS::EC2::Image::Id
#   (Value retrived via shell scrip)
# SSM method below but variable type not versatile to scripts. 
#  myAmi:
#    Description: The AMI to use for EC2 instances.
#    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
#    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SUBNET CIDR DEFINITIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#--- AZ-A Public Subnet
#-------------------------------------------
# Public Subnet A CIDR : 10.0.128.0/20

#--- AZ-B Public Subnet
#-------------------------------------------
# Public Subnet B CIDR : 10.0.144.0/20

#--- AZ-A Private Subnet
#-------------------------------------------
# Public Subnet A CIDR : 10.0.0.0/19

#--- AZ-B Private Subnet
#-------------------------------------------
# Public Subnet B CIDR : 10.0.32.0/19

#-------------------------------------------


#Conditions: {}
Conditions:
#===========================================  
  CreateResourcesStage0: !Equals [ !Ref BuildStage, Stage0]
  CreateResourcesStage1: !Equals [ !Ref BuildStage, Stage1]
  CreateResourcesStage2: !Equals [ !Ref BuildStage, Stage2]
  CreateResourcesStage3: !Equals [ !Ref BuildStage, Stage3]


Resources:
#===========================================

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# NESTED STACKS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- VPC Definition
#-------------------------------------------
  VPCDef:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-vpc.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        BuildStage:
          !Ref BuildStage
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Public/Private NACLs
#-------------------------------------------
  NaclDefs:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-nacl.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSubnetIdB:
          !GetAtt VPCDef.Outputs.PublicSubnetIdB
        PrivateSubnetIdA:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdA
        PrivateSubnetIdB:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdB
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Public/Private Security Groups
#-------------------------------------------
  SgDefs:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-sg.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
#        ApplicationName:
#          Ref: AWS::StackName
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Private/Public EC2 Instances
#-------------------------------------------
  InstancePub1Def:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage1
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-pub-1.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        PublicAmiId:
          !Ref CurrentAmi
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 10
#-------------------------------------------
  InstancePrivDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage1
    DependsOn: InstancePub1Def
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-priv.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        PrivateAmiId:
          !Ref CurrentAmi
        PrivateSubnetIdA:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdA
        PrivateSgResourceId:
          !GetAtt SgDefs.Outputs.PrivateSgResourceId
      TimeoutInMinutes: 10
#-------------------------------------------
  InstancePub2Def:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage2
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-pub-2.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        PublicAmiId:
          !Ref CurrentAmi
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 10
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- EC2 Launch Template
#-------------------------------------------
  LaunchTemplateDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-lt.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        PublicLtAmiId:
          !Ref CurrentAmi
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- EC2 Target Group
#-------------------------------------------
  TargetGroupDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-tg.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- EC2 AutoScaling Group
#-------------------------------------------
  AutoScaleGroupDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    DependsOn: 
      - LaunchTemplateDef
      - TargetGroupDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-asg.yaml
#,,,,,,,,,,,,,,,,
      Parameters:
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSubnetIdB:
          !GetAtt VPCDef.Outputs.PublicSubnetIdB
        LaunchTemplateIdASG:
          !GetAtt LaunchTemplateDef.Outputs.LaunchTemplateId
        TargetGroupArnNLB:
          !GetAtt TargetGroupDef.Outputs.TargetGroupArnNLB
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- EC2 Network Load Balancer 
#-------------------------------------------
  NetworkLoadBalancerDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    DependsOn: AutoScaleGroupDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-nlb.yaml
      Parameters:
#,,,,,,,,,,,,,,,,
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSubnetIdB:
          !GetAtt VPCDef.Outputs.PublicSubnetIdB
        TargetGroupArnNLB:
          !GetAtt TargetGroupDef.Outputs.TargetGroupArnNLB
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#-------------------------------------------


#Outputs: {}
Outputs:
#===========================================

#--- Instance IDs
#-------------------------------------------
  InstanceIdPublic1:
    Description:  Public Instance ID
    Condition: CreateResourcesStage1
    Value:
      !GetAtt InstancePub1Def.Outputs.Pub1EC2InstanceId
#-------------------------------------------
  InstanceIdPrivate:
    Description: Private Instance ID
    Condition: CreateResourcesStage1
    Value:
      !GetAtt InstancePrivDef.Outputs.PrivEC2InstanceId
#-------------------------------------------
  InstanceIdPublic2:
    Description:  Public Instance ID
    Condition: CreateResourcesStage2
    Value:
      !GetAtt InstancePub2Def.Outputs.Pub2EC2InstanceId
#-------------------------------------------

#  ExportsStackName:
#    Value: !Ref 'AWS::StackName'
#    Export:
#      Name: !Sub 'ExportsStackName-${AWS::StackName}'

