#https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-set1.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: >
  An OpenVPN implementation that comprises:
  Highly Available EC2 Instance bla bla.
  Autoscaling Group bla bla.
  Isolated Certificate Authority bla bla.
  Nested Stack as follows:
  Bla Bla.
  Inputs:
  Bla Bla.
  Outputs.
  Bla Bla.
#-------------------------------------------


Metadata: {}


Parameters:
#===========================================

#--- Stack Build Stage Indicator
#-------------------------------------------
  BuildStage: 
    Description: Openvpn infrastructure creation comprises various stages. 
    ConstraintDescription: Specify which Stage to provision.
    Default: Stage0
    Type: String
    AllowedValues: 
      - Stage0
      - Stage1
      - Stage2
      - Stage3

#--- Latest Amazon_Linux_2 AMI 
#-------------------------------------------
  CurrentAmi:
    Description: The AMI to use for EC2 instances.
    Type: AWS::EC2::Image::Id
#   (Value retrived via shell scrip)
# SSM method below but variable type not versatile to scripts. 
#  myAmi:
#    Description: The AMI to use for EC2 instances.
#    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
#    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# SUBNET CIDR DEFINITIONS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  VPCCIDR:
    Description: CIDR Block for the VPC
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Type: String
#--- AZ-A Public Subnet
#-------------------------------------------
  PublicSubnetACIDR:
    Description: CIDR Block for the public DMZ subnet A located in Availability Zone A.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Type: String
#--- AZ-B Public Subnet
#-------------------------------------------
  PublicSubnetBCIDR:
    Description: CIDR Block for the public DMZ subnet B located in Availability Zone B
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Type: String
#--- AZ-A Private Subnet
#-------------------------------------------
  PrivateSubnetACIDR:
    Description: CIDR block for private subnet A located in Availability Zone A.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Type: String
#--- AZ-B Private Subnet
#-------------------------------------------
  PrivateSubnetBCIDR:
    Description: CIDR block for private subnet B located in Availability Zone B.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Type: String
#-------------------------------------------


#Conditions: {}
Conditions:
  CreateResourcesStage0: !Equals [ !Ref BuildStage, Stage0]
  CreateResourcesStage1: !Equals [ !Ref BuildStage, Stage1]
  CreateResourcesStage2: !Equals [ !Ref BuildStage, Stage2]
  CreateResourcesStage3: !Equals [ !Ref BuildStage, Stage3]


Resources:

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# NESTED STACKS
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#--- VPC Definition
#-------------------------------------------
  VPCDef:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-vpc.yaml
      Parameters:
        BuildStage:
          !Ref BuildStage
        VPCCIDR:
          !Ref VPCCIDR
        PublicSubnetACIDR:
          !Ref PublicSubnetACIDR
        PublicSubnetBCIDR:
          !Ref PublicSubnetBCIDR
        PrivateSubnetACIDR:
          !Ref PrivateSubnetACIDR
        PrivateSubnetBCIDR:
          !Ref PrivateSubnetBCIDR
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Public/Private NACLs
#-------------------------------------------
  NaclDefs:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-nacl.yaml
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
        VPCCIDR:
          Ref: VPCCIDR          
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSubnetIdB:
          !GetAtt VPCDef.Outputs.PublicSubnetIdB
        PrivateSubnetIdA:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdA
        PrivateSubnetIdB:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdB
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Public/Private Security Groups
#-------------------------------------------
  SgDefs:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-sg.yaml
      Parameters:
        VPCID:
          !GetAtt VPCDef.Outputs.VPCID
        VPCCIDR:
          Ref: VPCCIDR
#        ApplicationName:
#          Ref: AWS::StackName
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Private/Public EC2 Instances
#-------------------------------------------
  InstancePubStage1Def:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage1
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-pub-stage1.yaml
      Parameters:
        PublicAmiId:
          !Ref CurrentAmi
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 10
#-------------------------------------------
  InstancePrivDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage1
    DependsOn: InstancePubStage1Def
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-priv.yaml
      Parameters:
        PrivateAmiId:
          !Ref CurrentAmi
        PrivateSubnetIdA:
          !GetAtt VPCDef.Outputs.PrivateSubnetIdA
        PrivateSgResourceId:
          !GetAtt SgDefs.Outputs.PrivateSgResourceId
      TimeoutInMinutes: 10
#-------------------------------------------
  InstancePubStage2Def:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage2
    DependsOn: VPCDef
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-pub-stage2.yaml
      Parameters:
        PublicAmiId:
          !Ref CurrentAmi
        PublicSubnetIdA:
          !GetAtt VPCDef.Outputs.PublicSubnetIdA
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 10
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#--- Public/Private NACLs
#-------------------------------------------
  LaunchTemplateDef:
    Type: AWS::CloudFormation::Stack
    Condition: CreateResourcesStage3
    Properties:
      TemplateURL: https://s3.eu-central-1.amazonaws.com/dh.cform-templates/openvpn/dh.cform.openvpn-ec2-lt.yaml
      Parameters:
        PublicLtAmiId:
          !Ref CurrentAmi
        PublicSgResourceId:
          !GetAtt SgDefs.Outputs.PublicSgResourceId
      TimeoutInMinutes: 5
#-------------------------------------------
#-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-o-


#-------------------------------------------

#Outputs: {}
Outputs:
#===========================================

#--- Instance IDs
#-------------------------------------------
  InstanceIdPubStage1:
    Description:  Public Instance ID
    Condition: CreateResourcesStage1
    Value:
      !GetAtt InstancePubStage1Def.Outputs.InstanceIdPubStage1Nested
#-------------------------------------------
  InstanceIdPrivate:
    Description: Private Instance ID
    Condition: CreateResourcesStage1
    Value:
      !GetAtt InstancePrivDef.Outputs.InstanceIdPrivateNested
#-------------------------------------------
  InstanceIdPubStage2:
    Description:  Public Instance ID
    Condition: CreateResourcesStage2
    Value:
      !GetAtt InstancePubStage2Def.Outputs.InstanceIdPubStage2Nested
#-------------------------------------------

#  ExportsStackName:
#    Value: !Ref 'AWS::StackName'
#    Export:
#      Name: !Sub 'ExportsStackName-${AWS::StackName}'

#--- VPC CIDR Export
#-------------------------------------------
#  VPCCIDR:
#    Description: VPC CIDR
#    Value:
#      Ref: VPCCIDR
#    Export:
#      Name:
#        Fn::Sub: ${AWS::StackName}-VPCCIDR

